### PR TITLE
Allow alternative author format using "@"

### PR DESCRIPTION
**Pull request by mayrholu**
Hi there, I have a suggestion for an alternative author format which we use in our projects. It would be helpful if that format could be supported as well. Thanks!

### CODE REVIEW

**Comment by orsinium** [comment]
What does it look like? Bring in some tests, please.

**Comment by mayrholu** [comment]
Sorry, forgot to commit the tests. Does it make sense now?

**Comment by orsinium** [comment]
Perfect, thank you :)

**Comment by orsinium** [comment]
Released as 0.3.0 ✅

**Pull request merged**
